### ISSUE TITLE
header.html: search input misplaced

### ISSUE THREAD

**Issue by anasamati** [the-engine-room/simsim-frontend#2]
Check mp-profile-after.html file to see it in action

**Comment by IronRunes** [comment]
This issue is raised by the concurrent loading of both nouabook.min.css and site.min.css.
please remove nouabook.min.css to see the search input float correctly.

**Comment by anasamati** [comment]
nouabook.min.css is global for the whole site, if i remove it, other pages will not displaying well.

**Comment by IronRunes** [comment]
is the header and navigation being redesigned selectively only for the new pages?

**Comment by anasamati** [comment]
The header is a master header, which means it is global

**Comment by IronRunes** [comment]
ok, i'll try changing class names and such to see if that fixes it.

**Comment by IronRunes** [comment]
I addressed this. 
There is some code referring specifically to input[type="search"] in nouabook.min.css that brought on that behaviour. 
I'd suggest that you remove all unneeded css rules for the global parts that has been redesigned.

**Comment by anasamati** [comment]
thanks, it is fixed now, but i should have change the _input type="search"_ into _type="text"_  in mp-profile.html in order to display well
